local suggestion = require("copilot.suggestion")

vim.keymap.set("i", "<C-l>", suggestion.accept_line, { noremap = true })
vim.keymap.set("i", "<C-w>", suggestion.accept_word, { noremap = true })
vim.keymap.set("i", "<Tab>", suggestion.accept, { noremap = true })
vim.keymap.set("i", "<C-j>", suggestion.next, { noremap = true })
vim.keymap.set("i", "<C-k>", suggestion.prev, { noremap = true })
-- require("copilot.suggestion").is_visible()
-- require("copilot.suggestion").accept(modifier)
-- require("copilot.suggestion").accept_word()
-- require("copilot.suggestion").accept_line()
-- require("copilot.suggestion").next()
-- require("copilot.suggestion").prev()
-- require("copilot.suggestion").dismiss()
-- require("copilot.suggestion").toggle_auto_trigger()
--
-- require("copilot.panel").accept()
-- require("copilot.panel").jump_next()
-- require("copilot.panel").jump_prev()
-- require("copilot.panel").open({position, ratio})
-- require("copilot.panel").refresh()
