print("plugin/example.lua is executed!")

-- local Popup = require("nui.popup")
-- local Layout = require("nui.layout")
--
-- local popup = Popup({
--   enter = true,
--   border = {
--     style = "rounded",
--     text = {
--       top = "Popup",
--       top_align = "center",
--     },
--   },
--   relative = "editor",
--   position = "50%",
--   size = {
--     width = 80,
--     height = 40,
--   },
-- })
--
-- local layout = Layout(
--   {
--     position = "50%",
--     size = {
--       width = 80,
--       height = "60%",
--     },
--   },
--   Layout.Box({
--     Layout.Box(popup, { size = "100%" }),
--   })
-- )
--
--
-- vim.keymap.set('n', '<leader>tt', function()
--   layout:mount()
-- end)
